config/routes.rb
Rails.application.routes.draw do
  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  unauthenticated do
    root to: 'home#index'

    as :user do
      get 'users', to: redirect('/users/login')
    end
  end

  authenticated do
    root to: 'account/churches#show'
  end

  authenticate do
    resource :search

    scope module: 'messages' do
      resources :messages do
        get :reply_to, on: :member, path: 'reply', action: 'reply'
        get :forward, on: :member
        get :sent, on: :collection
      end
    end

    namespace :calendar do
      # Oauth 2.0
      get 'redirect', to: 'calendars#redirect', as: 'redirect'
      get 'callback', to: 'calendars#callback', as: 'callback'

      resource :settings
    end

    scope module: 'calendar' do
      resource :calendar
    end

    scope module: 'families' do
      resources :families, concerns: :paginatable do
        get :confirm_destroy, on: :member
        resources :family_memberships, path: 'memberships'
        resource :merge
        get :merge, on: :collection
      end
    end

    scope module: 'people' do
      resources :teams, concerns: :paginatable do
        get :confirm_destroy, on: :member
        resources :team_memberships, path: 'memberships'
        resources :events, controller: '/events/events'
      end
      resources :people, concerns: :paginatable do
        get :confirm_destroy, on: :member
        get :import, on: :collection
        post :import, on: :collection

        resource :user do
          resource :password
        end

        resource :teams, controller: :person_teams
        resource :families, controller: :person_families
        resources :person_processes, path: 'processes'
        resource :merge
      end
      resources :properties, concerns: :paginatable do
        get :confirm_destroy, on: :member
      end
      resources :imports
    end

    scope module: 'events' do
      resources :events, concerns: :paginatable do
        get :confirm_destroy, on: :member
      end
    end

    scope module: 'processes' do
      resources :church_processes, concerns: :paginatable, path: 'processes' do
        get :confirm_destroy, on: :member
        resources :person_processes, path: 'people'
      end
    end

    scope module: 'children' do
      get 'children', to: redirect('children/groups')
      resources :child_groups, path: 'children/groups' do
        get :confirm_destroy, on: :member
        resources :child_group_memberships, path: 'memberships'
      end
    end

    namespace :kiosk do
      resources :child_groups, path: 'children/groups' do
        resources :child_group_memberships, path: 'memberships'
      end
      resources :check_ins
      resources :check_outs
    end

    namespace :account do
      get '/' => 'people#show'
      get 'welcome' => 'people#welcome', as: :welcome
      as :user do
        get 'resend_confirmation' => 'confirmations#resend'
      end
      resource :person
      resource :church
      resource :settings
    end

    scope module: 'comments' do
      resources :comments
    end
  end

  devise_for :users,
             sign_out_via: :get,
             controllers: {
               confirmations: 'account/confirmations',
               registrations: 'account/registrations',
               omniauth_callbacks: 'account/omniauth_callbacks'
             },
             path_names: {
               sign_in: 'login',
               sign_out: 'logout'
             }

end

app/models/child_group.rb
class ChildGroup < ApplicationRecord
  has_many :child_group_memberships,  dependent: :destroy
  has_many :people,                   through: :child_group_memberships

  validates_presence_of :name
  validates_uniqueness_of :name

  def to_s
    name
  end
end

app/controllers/children/child_groups_controller.rb
class Children::ChildGroupsController < ApplicationController
  load_and_authorize_resource

  def index
    @child_groups = @child_groups.page(params[:page]).per(20)
  end

  def create
    if @child_group.save
      redirect_to @child_group
    else
      render :new
    end
  end

  def update
    if @child_group.update_attributes create_params
      redirect_to @child_group
    else
      render :edit
    end
  end

  def destroy
    @child_group.destroy
    redirect_to child_groups_path, notice: "#{@child_group} has been removed from the database."
  end

  private

  def create_params
    params.require(:child_group).permit(:name, :age_group, :description)
  end
end

app/controllers/kiosk/check_ins_controller.rb
class Kiosk::CheckInsController < ApplicationController
  before_action :load_and_authorize_child_group_membership
  layout 'kiosk'

  def show
    @child_group_checkin = @child_group_membership.child_group_checkins.new
  end

  def update
    checked_in_by = params[:checked_in_by_id] ? Person.find(params[:checked_in_by_id]) : nil
    if @child_group_membership.check_in(checked_in_by)
      respond_to do |format|
        format.html { redirect_to kiosk_child_group_path(@child_group_membership.child_group) }
        format.js
      end
    else
      render :show
    end
  end

  private

  def load_child_group_checkin
    @child_group_checkin = @child_group_membership.child_group_checkins.new
  end

  def load_and_authorize_child_group_membership
    @child_group_membership = ChildGroupMembership.find(params[:id])
    authorize! :update, @child_group_membership.child_group
  end
end

app/controllers/kiosk/check_outs_controller.rb
class Kiosk::CheckOutsController < ApplicationController
  before_action :load_and_authorize_child_group_membership
  layout 'kiosk'

  def show
    @child_group_checkin = @child_group_membership.child_group_checkins.last
  end

  def update
    checked_out_by = params[:checked_out_by_id] ? Person.find(params[:checked_out_by_id]) : nil
    if @child_group_membership.check_out(checked_out_by)
      respond_to do |format|
        format.html { redirect_to kiosk_child_group_path(@child_group_membership.child_group) }
        format.js { render "kiosk/check_ins/update" }
      end
    else
      render :show
    end
  end

  private

  def load_and_authorize_child_group_membership
    @child_group_membership = ChildGroupMembership.find(params[:id])
    authorize! :update, @child_group_membership.child_group
  end
end

app/controllers/kiosk/child_group_memberships_controller.rb
class Kiosk::ChildGroupMembershipsController < Children::ChildGroupMembershipsController
  layout 'kiosk'

  def create
    @child_group_membership.child_group = @child_group
    if @child_group_membership.save
      start_family if create_params[:person].try(:[], :family_name).present?
      redirect_to kiosk_child_group_path(@child_group_membership.child_group)
    else
      @child_group_membership.person ||= Person.new
      render :new
    end
  end
end

app/controllers/kiosk/child_groups_controller.rb
class Kiosk::ChildGroupsController < ApplicationController
  load_and_authorize_resource
  layout 'kiosk'
end

app/views/kiosk/child_groups/_title.html.erb
<div class="title-container py-1 mb-1 text-xs-center title-container-0">

  <% if local_assigns[:icon] %>
    <div class="mb-sm hidden-xs-down">
      <span class="avatar avatar-xl avatar-icon">
        <%= icon_for icon %>
      </span>
    </div>
  <% end %>

  <h2 class="mb-0"><%= title %></h2>
</div>

app/views/kiosk/child_groups/show.html.erb
<div class="container py-2">
  <div class="float-xs-right">
    <%= link_to(new_kiosk_child_group_child_group_membership_path(@child_group), class: 'btn btn-outline-primary btn-lg btn-align-middle mr-sm') do %>
      <%= icon_for(:new, class: 'mr-xs') %>
      Add child
    <% end %>
    <%= link_to(@child_group, class: 'btn btn-secondary btn-lg btn-subtle btn-align-middle') do %>
      <%= icon_for(:x) %>
      <div class="sr-only">Close</div>
    <% end %>
  </div>

  <h1><%= @child_group %></h1>

  <% by_first_letter(@child_group.child_group_memberships.includes(:person)).each do |letter, memberships| %>
    <h2 class="my-1 pt-1 ml-2 pl-sm"><%= letter %></h2>

    <% memberships.each do |membership| %>
      <% if membership.checked_in? %>
        <%= link_to kiosk_check_out_path(membership), class: "btn btn-outline-warning btn-block text-xs-left p-2 size-md-huge clearfix" do %>
          <div class="avatar-md-container">
            <%= avatar_tag membership.person, class: 'avatar-md' %>
            <div class="float-xs-right mx-1">
              <span class="float-xs-left hidden-xs-down size-xs-normal text-light"><%= membership.child_group_checkins.last.checked_in_by %></span>
              <%= icon_for 'sign-out', class: 'ml-1' %>
            </div>
            <div class="pl-sm"><%= membership.person %></div>
          </div>
        <% end %>
      <% else %>
        <%= link_to kiosk_check_in_path(membership), class: "btn btn-secondary btn-block text-xs-left p-2 size-md-huge" do %>
          <div class="avatar-md-container">
            <%= avatar_tag membership.person, class: 'avatar-md' %>
            <div class="float-xs-right mx-1"><%= icon_for 'sign-in' %></div>
            <div class="pl-sm"><%= membership.person %></div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>