config/routes.rb
Rails.application.routes.draw do
  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  unauthenticated do
    root to: 'home#index'

    as :user do
      get 'users', to: redirect('/users/login')
    end
  end

  authenticated do
    root to: 'account/churches#show'
  end

  authenticate do
    resource :search

    scope module: 'messages' do
      resources :messages do
        get :reply_to, on: :member, path: 'reply', action: 'reply'
        get :forward, on: :member
        get :sent, on: :collection
      end
    end

    namespace :calendar do
      # Oauth 2.0
      get 'redirect', to: 'calendars#redirect', as: 'redirect'
      get 'callback', to: 'calendars#callback', as: 'callback'

      resource :settings
    end

    scope module: 'calendar' do
      resource :calendar
    end

    scope module: 'families' do
      resources :families, concerns: :paginatable do
        get :confirm_destroy, on: :member
        resources :family_memberships, path: 'memberships'
        resource :merge
        get :merge, on: :collection
      end
    end

    scope module: 'people' do
      resources :teams, concerns: :paginatable do
        get :confirm_destroy, on: :member
        resources :team_memberships, path: 'memberships'
        resources :events, controller: '/events/events'
      end
      resources :people, concerns: :paginatable do
        get :confirm_destroy, on: :member
        get :import, on: :collection
        post :import, on: :collection

        resource :user do
          resource :password
        end

        resource :teams, controller: :person_teams
        resource :families, controller: :person_families
        resources :person_processes, path: 'processes'
        resource :merge
      end
      resources :properties, concerns: :paginatable do
        get :confirm_destroy, on: :member
      end
      resources :imports
    end

    scope module: 'events' do
      resources :events, concerns: :paginatable do
        get :confirm_destroy, on: :member
      end
    end

    scope module: 'processes' do
      resources :church_processes, concerns: :paginatable, path: 'processes' do
        get :confirm_destroy, on: :member
        resources :person_processes, path: 'people'
      end
    end

    scope module: 'children' do
      get 'children', to: redirect('children/groups')
      resources :child_groups, path: 'children/groups' do
        get :confirm_destroy, on: :member
        resources :child_group_memberships, path: 'memberships'
      end
    end

    namespace :kiosk do
      resources :child_groups, path: 'children/groups' do
        resources :child_group_memberships, path: 'memberships'
      end
      resources :check_ins
      resources :check_outs
    end

    namespace :account do
      get '/' => 'people#show'
      get 'welcome' => 'people#welcome', as: :welcome
      as :user do
        get 'resend_confirmation' => 'confirmations#resend'
      end
      resource :person
      resource :church
      resource :settings
    end

    scope module: 'comments' do
      resources :comments
    end
  end

  devise_for :users,
             sign_out_via: :get,
             controllers: {
               confirmations: 'account/confirmations',
               registrations: 'account/registrations',
               omniauth_callbacks: 'account/omniauth_callbacks'
             },
             path_names: {
               sign_in: 'login',
               sign_out: 'logout'
             }

end

app/models/child_group_membership.rb
class ChildGroupMembership < ApplicationRecord
  delegate :to_s, :name, to: :person

  belongs_to :child_group
  belongs_to :person, autosave: true

  has_many :child_group_checkins, dependent: :destroy

  validates_presence_of :person, :child_group_id

  scope :checked_in, ->{ where(checked_in: true) }
  scope :checked_out, ->{ where(checked_in: false) }

  def check_in(check_in_by=nil)
    unless checked_in?
      child_group_checkins.create checked_in_by: check_in_by, checked_in_at: Time.now
      update_attributes checked_in: true
    end
  end

  def check_out(check_out_by=nil)
    unless checked_out?
      child_group_checkins.last.update_attributes checked_out_by: check_out_by, checked_out_at: Time.now
      update_attributes checked_in: false
    end
  end

  def checked_out?
    !checked_in?
  end

  def person=(person)
    if person.is_a?(Hash)
      super Person.new(person)
    else
      super
    end
  end
end

app/controllers/children/child_group_memberships_controller.rb
class Children::ChildGroupMembershipsController < ApplicationController
  load_and_authorize_resource
  before_action :load_and_authorize_child_group

  def new
    @child_group_membership.person = Person.new
    @child_group_membership.child_group = @child_group
  end

  def index
    redirect_to @child_group
  end

  def create
    @child_group_membership.child_group = @child_group
    if @child_group_membership.save
      start_family if create_params[:person].try(:[], :family_name).present?
      redirect_to @child_group
    else
      @child_group_membership.person ||= Person.new
      render :new
    end
  end

  def destroy
    @child_group_membership.destroy

    respond_to do |format|
      format.html { redirect_to @child_group }
      format.js
    end
  end

  private

  def create_params
    hash = blanks_to_nil params.require(:child_group_membership).permit :person_id, person: [
      :first_name, :middle_name, :last_name, :gender, :dob, :family_ids, :family_name, :family_address1, :family_address2, :family_postcode, :family_country, family_ids: []
    ]

    hash[:person].delete(:family_ids) if hash[:person].try(:[], :family_ids) == "New"
    hash[:person] = blanks_to_nil hash[:person]
    hash.delete(:person) unless hash[:person_id] == "New"
    hash.delete(:person_id) if hash[:person_id] == "New"
    hash
  end

  def load_and_authorize_child_group
    @child_group = ChildGroup.find(params[:child_group_id])
    authorize! :update, @child_group
  end

  def start_family
    @child_group_membership.person.start_family(create_params[:person]) if @child_group_membership.person.families.blank?
  end
end

app/controllers/children/child_groups_controller.rb
class Children::ChildGroupsController < ApplicationController
  load_and_authorize_resource

  def index
    @child_groups = @child_groups.page(params[:page]).per(20)
  end

  def create
    if @child_group.save
      redirect_to @child_group
    else
      render :new
    end
  end

  def update
    if @child_group.update_attributes create_params
      redirect_to @child_group
    else
      render :edit
    end
  end

  def destroy
    @child_group.destroy
    redirect_to child_groups_path, notice: "#{@child_group} has been removed from the database."
  end

  private

  def create_params
    params.require(:child_group).permit(:name, :age_group, :description)
  end
end

app/controllers/children/kiosk_check_ins_controller.rb
class Children::KioskCheckInsController < ApplicationController
  before_action :load_and_authorize_child_group_membership
  layout 'kiosk'

  def show
    @child_group_checkin = @child_group_membership.child_group_checkins.new
  end

  def update
    checked_in_by = params[:checked_in_by_id] ? Person.find(params[:checked_in_by_id]) : nil
    if @child_group_membership.check_in(checked_in_by)
      respond_to do |format|
        format.html { redirect_to child_group_kiosk_path(@child_group_membership.child_group) }
        format.js
      end
    else
      render :show
    end
  end

  private

  def load_child_group_checkin
    @child_group_checkin = @child_group_membership.child_group_checkins.new
  end

  def load_and_authorize_child_group_membership
    @child_group_membership = ChildGroupMembership.find(params[:id])
    authorize! :update, @child_group_membership.child_group
  end
end

app/controllers/children/kiosk_check_outs_controller.rb
class Children::KioskCheckOutsController < ApplicationController
  before_action :load_and_authorize_child_group_membership
  layout 'kiosk'

  def show
    @child_group_checkin = @child_group_membership.child_group_checkins.last
  end

  def update
    checked_out_by = params[:checked_out_by_id] ? Person.find(params[:checked_out_by_id]) : nil
    if @child_group_membership.check_out(checked_out_by)
      respond_to do |format|
        format.html { redirect_to child_group_kiosk_path(@child_group_membership.child_group) }
        format.js { render "children/kiosk_check_ins/update" }
      end
    else
      render :show
    end
  end

  private

  def load_and_authorize_child_group_membership
    @child_group_membership = ChildGroupMembership.find(params[:id])
    authorize! :update, @child_group_membership.child_group
  end
end

app/controllers/kiosk/child_group_memberships_controller.rb
class Kiosk::ChildGroupMembershipsController < Children::ChildGroupMembershipsController
  layout 'kiosk'

  def create
    @child_group_membership.child_group = @child_group
    if @child_group_membership.save
      start_family if create_params[:person].try(:[], :family_name).present?
      redirect_to kiosk_child_group_path(@child_group_membership.child_group)
    else
      @child_group_membership.person ||= Person.new
      render :new
    end
  end
end

app/views/children/child_group_memberships/_list_group_item.html.erb
<div class="list-group-item" id="child_group_membership_<%= list_group_item.id %>">
  <div class="avatar-container clearfix">
    <%= avatar_tag list_group_item.person %>

    <div class="float-xs-right">
      <% if can?(:update, list_group_item.child_group) %>
        <% if list_group_item.checked_in? %>
          <%= button_to(kiosk_check_out_path(list_group_item.id),
                        method: :put,
                        remote: true,
                        data: { tooltip: true},
                        form_class: 'float-xs-left mr-sm',
                        class: 'btn btn-outline-success btn-sm btn-align-middle',
                        title: 'Check out') { icon_for 'sign-out' } %>
        <% else %>
          <%= button_to(kiosk_check_in_path(list_group_item.id),
                        method: :put,
                        remote: true,
                        data: { tooltip: true},
                        form_class: 'float-xs-left mr-sm',
                        class: 'btn btn-outline-warning btn-sm btn-align-middle',
                        title: 'Check in') { icon_for 'sign-in' } %>
        <% end %>
      <% end %>

      <% if can?(:destroy, list_group_item) %>
        <div class="float-xs-left">
          <%= button_to [list_group_item.child_group, list_group_item], method: :delete, remote: true, class: 'btn btn-link btn-align-middle px-xs text-light', data: { confirm: "Really remove #{list_group_item.person} from #{list_group_item.child_group}?" } do %>
            <%= icon_for :x %>
          <% end %>
        </div>
      <% end %>
    </div>

    <%= link_to list_group_item, [list_group_item.child_group, list_group_item], class: "float-sm-left mr-sm size-xs-small size-sm-normal #{'text-warning' if list_group_item.checked_in?}" %>

    <% if list_group_item.person.dob %>
      <div class="float-sm-right mr-1">
        <span class="size-xs-tiny text-light">
          <%= list_group_item.person.age %>
        </span>
      </div>
    <% end %>

  </div>
</div>

app/views/children/child_group_memberships/_menu.html.erb
<% content_for :menu, :children %>

<% if @child_group_membership.try(:persisted?) %>
  <%= render 'shared/side_and_details',
             title: local_assigns[:title],
             active: local_assigns[:active],
             items: [{ title: "Children", icon: :search, href: :child_groups },
                     '-',
                     ({ title: @child_group_membership.child_group, icon: @child_group_membership.child_group,  href: @child_group_membership.child_group }),
                     ({ title: 'Edit',                              icon: :edit,                                href: edit_child_group_path(@child_group_membership.child_group)}                       if can?(:update, @child_group_membership.child_group)),
                     ({ title: 'Add child',                         icon: :person,                              href: new_child_group_child_group_membership_path(@child_group_membership.child_group)} if can?(:create, ChildGroupMembership)),
                     ({ title: 'Kiosk / Tablet mode',               icon: :laptop,                              href: kiosk_child_group_path(@child_group_membership.child_group)}),
                     ({ title: 'Remove group',                      icon: :destroy,                             href: confirm_destroy_child_group_path(@child_group)}                                   if can?(:destroy, @child_group)),
                     '-',
                     ({ title: @child_group_membership.person.first_name, icon: @child_group_membership.person,       href: child_group_child_group_membership_path(@child_group_membership.child_group, @child_group_membership)})
  ] { yield } %>
<% else %>
  <%= render 'children/child_groups/menu',
             title:  local_assigns[:title],
             active: local_assigns[:active],
             items:  local_assigns[:menu] { yield } %>
<% end %>

app/views/children/child_group_memberships/_title.html.erb
<% unless local_assigns[:icon] %>
  <div class="text-xs-center mb-sm">
    <%= avatar_tag @child_group_membership.person, class: 'avatar-xl' %>
  </div>
<% end %>

<%= render 'shared/title',
           title: local_assigns[:title] || @child_group_membership.person,
           href: local_assigns[:href],
           icon: local_assigns[:title] %>

app/views/children/child_group_memberships/destroy.js.erb
$('#child_group_membership_<%= @child_group_membership.id %>').slideUp(150);

app/views/children/child_group_memberships/new.html.erb
<%= render 'menu', title: 'Add child', active: :person do %>

  <p class="alert alert-info">
    Adding children to your group allows parents to check in their child, and then pick them up later.
  </p>

  <%= form_for @child_group_membership, url: child_group_child_group_memberships_path(@child_group) do |f| %>
    <div class="list-group mb-2">
      <%= render 'shared/list_group_header', title: 'Child' %>

      <div class="list-group-item">
        <div class="">
          Choose a child from the database, or register a new one.
        </div>
        <div class="my-sm">
          <%= f.select :person_id, [], { include_blank: true },
                       class: 'form-control',
                       data: { selectpicker: true, placeholder: 'Choose a person', :'allow-clear' => true, new: 'Register new child', ajax: people_path, template: :child } %>
        </div>
      </div>
    </div>

    <div class="list-group mb-2" id="child_group_membership_new_child">
      <%= render 'shared/list_group_header', title: 'Add child' %>
      <%= f.fields_for @child_group_membership.person do |p| %>
        <%= render 'children/people/form_fields', f: p %>
      <% end %>
    </div>

    <%= render 'shared/form_submit', icon: @child_group_membership, title: "Add child" %>
  <% end %>

<% end %>

app/views/children/child_group_memberships/show.html.erb
<%= render 'menu', title: @child_group_membership.person, active: @child_group_membership.person do %>
  <div class="list-group mb-2">
    <%= render 'shared/list_group_header', title: 'Check-in History' %>

    <% by_date(@child_group_membership.child_group_checkins).each do |date, checkins| %>
      <div class="list-group-item size-xs-small size-sm-normal">
        <h4><%= date %></h4>
        <% checkins.each_with_index do |checkin, index| %>

          <% if index > 0 %>
            <hr class="my-sm" />
          <% end %>

          <div class="check-in">
            <div class="check-in-time"><%= checkin.checked_in_at.strftime('%H:%M') %></div>
            <span class="text-warning">
              <%= icon_for 'sign-in' %>
              <span class="hidden-xs-down">Checked in</span>
            </span>

            <% if checkin.checked_in_by %>
              by <%= link_to_if can?(:read, checkin.checked_in_by), checkin.checked_in_by, checkin.checked_in_by %>
            <% end %>
          </div>

          <% if checkin.checked_out_at %>
            <div class="check-out">
              <div class="check-out-time"><%= checkin.checked_out_at.strftime('%H:%M') %></div>
              <span class="text-success">
                <%= icon_for 'sign-out' %>
                <span class="hidden-xs-down">Picked up</span>
              </span>
              <% if checkin.checked_out_by %>
                by <%= link_to_if can?(:read, checkin.checked_out_by), checkin.checked_out_by, checkin.checked_out_by %>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>